<?php

namespace api\modules\v1\controllers;

use Yii;
use \yii\rest\Controller;
use yii\web\Response;

class RestfulController extends Controller
{
    protected function verbs()
    {
        return [
            'index' => ['POST'],
        ];
    }

    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionIndex($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        return [
            'data' => [
                'id' => $id,
                'message' => 'success',
                'code' => 200,
            ],
        ];
    }
}
